// AUTO-GENERATED by build-products.mjs — do not edit by hand.
export default {
  "ai-hangasszisztens-prompt-csomag": {
    "hu": "AI Hangasszisztens Prompt-csomag",
    "en": "AI Voice Assistant Prompt Pack"
  },
  "email-triage-workflow-n8n": {
    "hu": "E-mail Triage Workflow (n8n)",
    "en": "Email Triage Workflow (n8n)"
  },
  "cold-email-szekvencia-pack": {
    "hu": "Cold Email Szekvencia Pack",
    "en": "Cold Email Sequence Pack"
  },
  "crm-szinkron-sablon-make": {
    "hu": "CRM Szinkron Sablon (Make.com)",
    "en": "CRM Sync Template (Make.com)"
  },
  "ai-ugyfelszolgalati-chatbot-kit": {
    "hu": "AI Ügyfélszolgálati Chatbot Kit",
    "en": "AI Customer Support Chatbot Kit"
  },
  "ai-automatizalas-kisvallalkozasoknak-ebook": {
    "hu": "AI Automatizálás Kisvállalkozásoknak (E-book)",
    "en": "AI Automation for Small Business (E-book)"
  },
  "szamlazas-automatizalas-workflow-n8n": {
    "hu": "Számlázás Automatizálás Workflow (n8n)",
    "en": "Invoicing Automation Workflow (n8n)"
  },
  "lead-minosito-ai-prompt-csomag": {
    "hu": "Lead Minősítő AI Prompt-csomag",
    "en": "Lead Qualification AI Prompt Pack"
  },
  "ai-automatizalas-jatekkonyve": {
    "hu": "Az AI Automatizálás Játékkönyve (Playbook)",
    "en": "The AI Automation Playbook"
  }
};
